// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#include "message.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_message_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Host_message_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_google_2fprotobuf_2fstruct_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ListValue_google_2fprotobuf_2fstruct_2eproto;
namespace MyRpc {
class HostDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Host> _instance;
} _Host_default_instance_;
class RpcRequestPbDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RpcRequestPb> _instance;
} _RpcRequestPb_default_instance_;
class RpcResponsePbDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RpcResponsePb> _instance;
} _RpcResponsePb_default_instance_;
class TopicRequestPbDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TopicRequestPb> _instance;
} _TopicRequestPb_default_instance_;
class TopicResponsePbDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TopicResponsePb> _instance;
} _TopicResponsePb_default_instance_;
class ServiceRequestPbDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ServiceRequestPb> _instance;
} _ServiceRequestPb_default_instance_;
class ServiceResponsePbDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ServiceResponsePb> _instance;
} _ServiceResponsePb_default_instance_;
}  // namespace MyRpc
static void InitDefaultsscc_info_Host_message_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MyRpc::_Host_default_instance_;
    new (ptr) ::MyRpc::Host();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MyRpc::Host::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Host_message_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Host_message_2eproto}, {}};

static void InitDefaultsscc_info_RpcRequestPb_message_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MyRpc::_RpcRequestPb_default_instance_;
    new (ptr) ::MyRpc::RpcRequestPb();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MyRpc::RpcRequestPb::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_RpcRequestPb_message_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_RpcRequestPb_message_2eproto}, {
      &scc_info_ListValue_google_2fprotobuf_2fstruct_2eproto.base,}};

static void InitDefaultsscc_info_RpcResponsePb_message_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MyRpc::_RpcResponsePb_default_instance_;
    new (ptr) ::MyRpc::RpcResponsePb();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MyRpc::RpcResponsePb::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_RpcResponsePb_message_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_RpcResponsePb_message_2eproto}, {
      &scc_info_ListValue_google_2fprotobuf_2fstruct_2eproto.base,}};

static void InitDefaultsscc_info_ServiceRequestPb_message_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MyRpc::_ServiceRequestPb_default_instance_;
    new (ptr) ::MyRpc::ServiceRequestPb();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MyRpc::ServiceRequestPb::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ServiceRequestPb_message_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_ServiceRequestPb_message_2eproto}, {
      &scc_info_Host_message_2eproto.base,}};

static void InitDefaultsscc_info_ServiceResponsePb_message_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MyRpc::_ServiceResponsePb_default_instance_;
    new (ptr) ::MyRpc::ServiceResponsePb();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MyRpc::ServiceResponsePb::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ServiceResponsePb_message_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_ServiceResponsePb_message_2eproto}, {
      &scc_info_Host_message_2eproto.base,}};

static void InitDefaultsscc_info_TopicRequestPb_message_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MyRpc::_TopicRequestPb_default_instance_;
    new (ptr) ::MyRpc::TopicRequestPb();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MyRpc::TopicRequestPb::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_TopicRequestPb_message_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_TopicRequestPb_message_2eproto}, {}};

static void InitDefaultsscc_info_TopicResponsePb_message_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MyRpc::_TopicResponsePb_default_instance_;
    new (ptr) ::MyRpc::TopicResponsePb();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MyRpc::TopicResponsePb::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_TopicResponsePb_message_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_TopicResponsePb_message_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_message_2eproto[7];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_message_2eproto[4];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_message_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_message_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MyRpc::Host, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::MyRpc::Host, ip_),
  PROTOBUF_FIELD_OFFSET(::MyRpc::Host, port_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MyRpc::RpcRequestPb, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::MyRpc::RpcRequestPb, method_),
  PROTOBUF_FIELD_OFFSET(::MyRpc::RpcRequestPb, parameters_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MyRpc::RpcResponsePb, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::MyRpc::RpcResponsePb, rcode_),
  PROTOBUF_FIELD_OFFSET(::MyRpc::RpcResponsePb, result_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MyRpc::TopicRequestPb, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::MyRpc::TopicRequestPb, topic_key_),
  PROTOBUF_FIELD_OFFSET(::MyRpc::TopicRequestPb, optype_),
  PROTOBUF_FIELD_OFFSET(::MyRpc::TopicRequestPb, topic_msg_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MyRpc::TopicResponsePb, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::MyRpc::TopicResponsePb, rcode_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MyRpc::ServiceRequestPb, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::MyRpc::ServiceRequestPb, method_),
  PROTOBUF_FIELD_OFFSET(::MyRpc::ServiceRequestPb, optype_),
  PROTOBUF_FIELD_OFFSET(::MyRpc::ServiceRequestPb, host_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MyRpc::ServiceResponsePb, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::MyRpc::ServiceResponsePb, rcode_),
  PROTOBUF_FIELD_OFFSET(::MyRpc::ServiceResponsePb, optype_),
  PROTOBUF_FIELD_OFFSET(::MyRpc::ServiceResponsePb, method_),
  PROTOBUF_FIELD_OFFSET(::MyRpc::ServiceResponsePb, hosts_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::MyRpc::Host)},
  { 7, -1, sizeof(::MyRpc::RpcRequestPb)},
  { 14, -1, sizeof(::MyRpc::RpcResponsePb)},
  { 21, -1, sizeof(::MyRpc::TopicRequestPb)},
  { 29, -1, sizeof(::MyRpc::TopicResponsePb)},
  { 35, -1, sizeof(::MyRpc::ServiceRequestPb)},
  { 43, -1, sizeof(::MyRpc::ServiceResponsePb)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::MyRpc::_Host_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::MyRpc::_RpcRequestPb_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::MyRpc::_RpcResponsePb_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::MyRpc::_TopicRequestPb_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::MyRpc::_TopicResponsePb_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::MyRpc::_ServiceRequestPb_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::MyRpc::_ServiceResponsePb_default_instance_),
};

const char descriptor_table_protodef_message_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rmessage.proto\022\005MyRpc\032\034google/protobuf/"
  "struct.proto\" \n\004Host\022\n\n\002ip\030\001 \001(\t\022\014\n\004port"
  "\030\002 \001(\005\"K\n\014RpcRequestPb\022\016\n\006method\030\001 \001(\t\022+"
  "\n\nparameters\030\002 \001(\0132\027.google.protobuf.Str"
  "uct\"F\n\rRpcResponsePb\022\r\n\005rcode\030\001 \001(\005\022&\n\006r"
  "esult\030\002 \001(\0132\026.google.protobuf.Value\"F\n\016T"
  "opicRequestPb\022\021\n\ttopic_key\030\001 \001(\t\022\016\n\006opty"
  "pe\030\002 \001(\005\022\021\n\ttopic_msg\030\003 \001(\t\" \n\017TopicResp"
  "onsePb\022\r\n\005rcode\030\001 \001(\005\"M\n\020ServiceRequestP"
  "b\022\016\n\006method\030\001 \001(\t\022\016\n\006optype\030\002 \001(\005\022\031\n\004hos"
  "t\030\003 \001(\0132\013.MyRpc.Host\"^\n\021ServiceResponseP"
  "b\022\r\n\005rcode\030\001 \001(\005\022\016\n\006optype\030\002 \001(\005\022\016\n\006meth"
  "od\030\003 \001(\t\022\032\n\005hosts\030\004 \003(\0132\013.MyRpc.Host*a\n\005"
  "Mtype\022\013\n\007REQ_RPC\020\000\022\017\n\013REQ_SERVICE\020\001\022\r\n\tR"
  "EQ_TOPIC\020\002\022\013\n\007RSP_RPC\020\003\022\r\n\tRSP_TOPIC\020\004\022\017"
  "\n\013RSP_SERVICE\020\005*\225\002\n\005Rcode\022\014\n\010RCODE_OK\020\000\022"
  "\026\n\022RCODE_PARSE_FAILED\020\001\022\027\n\023RCODE_ERROR_M"
  "SGTYPE\020\002\022\025\n\021RCODE_INVALID_MSG\020\003\022\026\n\022RCODE"
  "_DISCONNECTED\020\004\022\030\n\024RCODE_INVALID_PARAMS\020"
  "\005\022\033\n\027RCODE_NOT_FOUND_SERVICE\020\006\022\030\n\024RCODE_"
  "INVALID_OPTYPE\020\007\022\031\n\025RCODE_NOT_FOUND_TOPI"
  "C\020\010\022\030\n\024RCODE_INTERNAL_ERROR\020\t\022\030\n\024RCODE_I"
  "NVALID_RESULT\020\n*\177\n\013TopicOptype\022\020\n\014TOPIC_"
  "CREATE\020\000\022\020\n\014TOPIC_REMOVE\020\001\022\023\n\017TOPIC_SUBS"
  "CRIBE\020\002\022\020\n\014TOPIC_CANCEL\020\003\022\021\n\rTOPIC_PUBLI"
  "SH\020\004\022\022\n\016SERVICE_UNKNOW\020\005*|\n\rServiceOptyp"
  "e\022\024\n\020SERVICE_REGISTRY\020\000\022\025\n\021SERVICE_DISCO"
  "VERY\020\001\022\022\n\016SERVICE_ONLINE\020\002\022\023\n\017SERVICE_OF"
  "FLINE\020\003\022\025\n\021SERVICE_UNKNOW_PB\020\004b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_message_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fstruct_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_message_2eproto_sccs[7] = {
  &scc_info_Host_message_2eproto.base,
  &scc_info_RpcRequestPb_message_2eproto.base,
  &scc_info_RpcResponsePb_message_2eproto.base,
  &scc_info_ServiceRequestPb_message_2eproto.base,
  &scc_info_ServiceResponsePb_message_2eproto.base,
  &scc_info_TopicRequestPb_message_2eproto.base,
  &scc_info_TopicResponsePb_message_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_message_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2eproto = {
  false, false, descriptor_table_protodef_message_2eproto, "message.proto", 1158,
  &descriptor_table_message_2eproto_once, descriptor_table_message_2eproto_sccs, descriptor_table_message_2eproto_deps, 7, 1,
  schemas, file_default_instances, TableStruct_message_2eproto::offsets,
  file_level_metadata_message_2eproto, 7, file_level_enum_descriptors_message_2eproto, file_level_service_descriptors_message_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_message_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_message_2eproto)), true);
namespace MyRpc {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Mtype_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_message_2eproto);
  return file_level_enum_descriptors_message_2eproto[0];
}
bool Mtype_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Rcode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_message_2eproto);
  return file_level_enum_descriptors_message_2eproto[1];
}
bool Rcode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TopicOptype_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_message_2eproto);
  return file_level_enum_descriptors_message_2eproto[2];
}
bool TopicOptype_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ServiceOptype_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_message_2eproto);
  return file_level_enum_descriptors_message_2eproto[3];
}
bool ServiceOptype_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void Host::InitAsDefaultInstance() {
}
class Host::_Internal {
 public:
};

Host::Host(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyRpc.Host)
}
Host::Host(const Host& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ip_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_ip().empty()) {
    ip_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_ip(),
      GetArena());
  }
  port_ = from.port_;
  // @@protoc_insertion_point(copy_constructor:MyRpc.Host)
}

void Host::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Host_message_2eproto.base);
  ip_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  port_ = 0;
}

Host::~Host() {
  // @@protoc_insertion_point(destructor:MyRpc.Host)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Host::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  ip_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Host::ArenaDtor(void* object) {
  Host* _this = reinterpret_cast< Host* >(object);
  (void)_this;
}
void Host::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Host::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Host& Host::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Host_message_2eproto.base);
  return *internal_default_instance();
}


void Host::Clear() {
// @@protoc_insertion_point(message_clear_start:MyRpc.Host)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ip_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  port_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Host::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string ip = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_ip();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "MyRpc.Host.ip"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 port = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Host::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MyRpc.Host)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ip = 1;
  if (this->ip().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ip().data(), static_cast<int>(this->_internal_ip().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "MyRpc.Host.ip");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_ip(), target);
  }

  // int32 port = 2;
  if (this->port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_port(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyRpc.Host)
  return target;
}

size_t Host::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyRpc.Host)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string ip = 1;
  if (this->ip().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ip());
  }

  // int32 port = 2;
  if (this->port() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_port());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Host::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MyRpc.Host)
  GOOGLE_DCHECK_NE(&from, this);
  const Host* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Host>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MyRpc.Host)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MyRpc.Host)
    MergeFrom(*source);
  }
}

void Host::MergeFrom(const Host& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MyRpc.Host)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.ip().size() > 0) {
    _internal_set_ip(from._internal_ip());
  }
  if (from.port() != 0) {
    _internal_set_port(from._internal_port());
  }
}

void Host::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MyRpc.Host)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Host::CopyFrom(const Host& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyRpc.Host)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Host::IsInitialized() const {
  return true;
}

void Host::InternalSwap(Host* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ip_.Swap(&other->ip_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(port_, other->port_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Host::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void RpcRequestPb::InitAsDefaultInstance() {
  ::MyRpc::_RpcRequestPb_default_instance_._instance.get_mutable()->parameters_ = const_cast< PROTOBUF_NAMESPACE_ID::Struct*>(
      PROTOBUF_NAMESPACE_ID::Struct::internal_default_instance());
}
class RpcRequestPb::_Internal {
 public:
  static const PROTOBUF_NAMESPACE_ID::Struct& parameters(const RpcRequestPb* msg);
};

const PROTOBUF_NAMESPACE_ID::Struct&
RpcRequestPb::_Internal::parameters(const RpcRequestPb* msg) {
  return *msg->parameters_;
}
void RpcRequestPb::clear_parameters() {
  if (GetArena() == nullptr && parameters_ != nullptr) {
    delete parameters_;
  }
  parameters_ = nullptr;
}
RpcRequestPb::RpcRequestPb(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyRpc.RpcRequestPb)
}
RpcRequestPb::RpcRequestPb(const RpcRequestPb& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  method_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_method().empty()) {
    method_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_method(),
      GetArena());
  }
  if (from._internal_has_parameters()) {
    parameters_ = new PROTOBUF_NAMESPACE_ID::Struct(*from.parameters_);
  } else {
    parameters_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:MyRpc.RpcRequestPb)
}

void RpcRequestPb::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_RpcRequestPb_message_2eproto.base);
  method_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  parameters_ = nullptr;
}

RpcRequestPb::~RpcRequestPb() {
  // @@protoc_insertion_point(destructor:MyRpc.RpcRequestPb)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RpcRequestPb::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  method_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete parameters_;
}

void RpcRequestPb::ArenaDtor(void* object) {
  RpcRequestPb* _this = reinterpret_cast< RpcRequestPb* >(object);
  (void)_this;
}
void RpcRequestPb::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RpcRequestPb::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RpcRequestPb& RpcRequestPb::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RpcRequestPb_message_2eproto.base);
  return *internal_default_instance();
}


void RpcRequestPb::Clear() {
// @@protoc_insertion_point(message_clear_start:MyRpc.RpcRequestPb)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  method_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  if (GetArena() == nullptr && parameters_ != nullptr) {
    delete parameters_;
  }
  parameters_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RpcRequestPb::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string method = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_method();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "MyRpc.RpcRequestPb.method"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .google.protobuf.Struct parameters = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_parameters(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RpcRequestPb::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MyRpc.RpcRequestPb)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string method = 1;
  if (this->method().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_method().data(), static_cast<int>(this->_internal_method().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "MyRpc.RpcRequestPb.method");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_method(), target);
  }

  // .google.protobuf.Struct parameters = 2;
  if (this->has_parameters()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::parameters(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyRpc.RpcRequestPb)
  return target;
}

size_t RpcRequestPb::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyRpc.RpcRequestPb)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string method = 1;
  if (this->method().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_method());
  }

  // .google.protobuf.Struct parameters = 2;
  if (this->has_parameters()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *parameters_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RpcRequestPb::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MyRpc.RpcRequestPb)
  GOOGLE_DCHECK_NE(&from, this);
  const RpcRequestPb* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RpcRequestPb>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MyRpc.RpcRequestPb)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MyRpc.RpcRequestPb)
    MergeFrom(*source);
  }
}

void RpcRequestPb::MergeFrom(const RpcRequestPb& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MyRpc.RpcRequestPb)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.method().size() > 0) {
    _internal_set_method(from._internal_method());
  }
  if (from.has_parameters()) {
    _internal_mutable_parameters()->PROTOBUF_NAMESPACE_ID::Struct::MergeFrom(from._internal_parameters());
  }
}

void RpcRequestPb::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MyRpc.RpcRequestPb)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RpcRequestPb::CopyFrom(const RpcRequestPb& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyRpc.RpcRequestPb)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RpcRequestPb::IsInitialized() const {
  return true;
}

void RpcRequestPb::InternalSwap(RpcRequestPb* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  method_.Swap(&other->method_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(parameters_, other->parameters_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RpcRequestPb::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void RpcResponsePb::InitAsDefaultInstance() {
  ::MyRpc::_RpcResponsePb_default_instance_._instance.get_mutable()->result_ = const_cast< PROTOBUF_NAMESPACE_ID::Value*>(
      PROTOBUF_NAMESPACE_ID::Value::internal_default_instance());
}
class RpcResponsePb::_Internal {
 public:
  static const PROTOBUF_NAMESPACE_ID::Value& result(const RpcResponsePb* msg);
};

const PROTOBUF_NAMESPACE_ID::Value&
RpcResponsePb::_Internal::result(const RpcResponsePb* msg) {
  return *msg->result_;
}
void RpcResponsePb::clear_result() {
  if (GetArena() == nullptr && result_ != nullptr) {
    delete result_;
  }
  result_ = nullptr;
}
RpcResponsePb::RpcResponsePb(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyRpc.RpcResponsePb)
}
RpcResponsePb::RpcResponsePb(const RpcResponsePb& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_result()) {
    result_ = new PROTOBUF_NAMESPACE_ID::Value(*from.result_);
  } else {
    result_ = nullptr;
  }
  rcode_ = from.rcode_;
  // @@protoc_insertion_point(copy_constructor:MyRpc.RpcResponsePb)
}

void RpcResponsePb::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_RpcResponsePb_message_2eproto.base);
  ::memset(&result_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&rcode_) -
      reinterpret_cast<char*>(&result_)) + sizeof(rcode_));
}

RpcResponsePb::~RpcResponsePb() {
  // @@protoc_insertion_point(destructor:MyRpc.RpcResponsePb)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RpcResponsePb::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete result_;
}

void RpcResponsePb::ArenaDtor(void* object) {
  RpcResponsePb* _this = reinterpret_cast< RpcResponsePb* >(object);
  (void)_this;
}
void RpcResponsePb::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RpcResponsePb::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RpcResponsePb& RpcResponsePb::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RpcResponsePb_message_2eproto.base);
  return *internal_default_instance();
}


void RpcResponsePb::Clear() {
// @@protoc_insertion_point(message_clear_start:MyRpc.RpcResponsePb)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && result_ != nullptr) {
    delete result_;
  }
  result_ = nullptr;
  rcode_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RpcResponsePb::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 rcode = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          rcode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .google.protobuf.Value result = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_result(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RpcResponsePb::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MyRpc.RpcResponsePb)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 rcode = 1;
  if (this->rcode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_rcode(), target);
  }

  // .google.protobuf.Value result = 2;
  if (this->has_result()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::result(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyRpc.RpcResponsePb)
  return target;
}

size_t RpcResponsePb::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyRpc.RpcResponsePb)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .google.protobuf.Value result = 2;
  if (this->has_result()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *result_);
  }

  // int32 rcode = 1;
  if (this->rcode() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_rcode());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RpcResponsePb::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MyRpc.RpcResponsePb)
  GOOGLE_DCHECK_NE(&from, this);
  const RpcResponsePb* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RpcResponsePb>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MyRpc.RpcResponsePb)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MyRpc.RpcResponsePb)
    MergeFrom(*source);
  }
}

void RpcResponsePb::MergeFrom(const RpcResponsePb& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MyRpc.RpcResponsePb)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_result()) {
    _internal_mutable_result()->PROTOBUF_NAMESPACE_ID::Value::MergeFrom(from._internal_result());
  }
  if (from.rcode() != 0) {
    _internal_set_rcode(from._internal_rcode());
  }
}

void RpcResponsePb::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MyRpc.RpcResponsePb)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RpcResponsePb::CopyFrom(const RpcResponsePb& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyRpc.RpcResponsePb)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RpcResponsePb::IsInitialized() const {
  return true;
}

void RpcResponsePb::InternalSwap(RpcResponsePb* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RpcResponsePb, rcode_)
      + sizeof(RpcResponsePb::rcode_)
      - PROTOBUF_FIELD_OFFSET(RpcResponsePb, result_)>(
          reinterpret_cast<char*>(&result_),
          reinterpret_cast<char*>(&other->result_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RpcResponsePb::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void TopicRequestPb::InitAsDefaultInstance() {
}
class TopicRequestPb::_Internal {
 public:
};

TopicRequestPb::TopicRequestPb(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyRpc.TopicRequestPb)
}
TopicRequestPb::TopicRequestPb(const TopicRequestPb& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  topic_key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_topic_key().empty()) {
    topic_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_topic_key(),
      GetArena());
  }
  topic_msg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_topic_msg().empty()) {
    topic_msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_topic_msg(),
      GetArena());
  }
  optype_ = from.optype_;
  // @@protoc_insertion_point(copy_constructor:MyRpc.TopicRequestPb)
}

void TopicRequestPb::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_TopicRequestPb_message_2eproto.base);
  topic_key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  topic_msg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  optype_ = 0;
}

TopicRequestPb::~TopicRequestPb() {
  // @@protoc_insertion_point(destructor:MyRpc.TopicRequestPb)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void TopicRequestPb::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  topic_key_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  topic_msg_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void TopicRequestPb::ArenaDtor(void* object) {
  TopicRequestPb* _this = reinterpret_cast< TopicRequestPb* >(object);
  (void)_this;
}
void TopicRequestPb::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TopicRequestPb::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TopicRequestPb& TopicRequestPb::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_TopicRequestPb_message_2eproto.base);
  return *internal_default_instance();
}


void TopicRequestPb::Clear() {
// @@protoc_insertion_point(message_clear_start:MyRpc.TopicRequestPb)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  topic_key_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  topic_msg_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  optype_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TopicRequestPb::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string topic_key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_topic_key();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "MyRpc.TopicRequestPb.topic_key"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 optype = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          optype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string topic_msg = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_topic_msg();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "MyRpc.TopicRequestPb.topic_msg"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* TopicRequestPb::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MyRpc.TopicRequestPb)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string topic_key = 1;
  if (this->topic_key().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_topic_key().data(), static_cast<int>(this->_internal_topic_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "MyRpc.TopicRequestPb.topic_key");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_topic_key(), target);
  }

  // int32 optype = 2;
  if (this->optype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_optype(), target);
  }

  // string topic_msg = 3;
  if (this->topic_msg().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_topic_msg().data(), static_cast<int>(this->_internal_topic_msg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "MyRpc.TopicRequestPb.topic_msg");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_topic_msg(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyRpc.TopicRequestPb)
  return target;
}

size_t TopicRequestPb::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyRpc.TopicRequestPb)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string topic_key = 1;
  if (this->topic_key().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_topic_key());
  }

  // string topic_msg = 3;
  if (this->topic_msg().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_topic_msg());
  }

  // int32 optype = 2;
  if (this->optype() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_optype());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TopicRequestPb::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MyRpc.TopicRequestPb)
  GOOGLE_DCHECK_NE(&from, this);
  const TopicRequestPb* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<TopicRequestPb>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MyRpc.TopicRequestPb)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MyRpc.TopicRequestPb)
    MergeFrom(*source);
  }
}

void TopicRequestPb::MergeFrom(const TopicRequestPb& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MyRpc.TopicRequestPb)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.topic_key().size() > 0) {
    _internal_set_topic_key(from._internal_topic_key());
  }
  if (from.topic_msg().size() > 0) {
    _internal_set_topic_msg(from._internal_topic_msg());
  }
  if (from.optype() != 0) {
    _internal_set_optype(from._internal_optype());
  }
}

void TopicRequestPb::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MyRpc.TopicRequestPb)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TopicRequestPb::CopyFrom(const TopicRequestPb& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyRpc.TopicRequestPb)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TopicRequestPb::IsInitialized() const {
  return true;
}

void TopicRequestPb::InternalSwap(TopicRequestPb* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  topic_key_.Swap(&other->topic_key_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  topic_msg_.Swap(&other->topic_msg_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(optype_, other->optype_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TopicRequestPb::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void TopicResponsePb::InitAsDefaultInstance() {
}
class TopicResponsePb::_Internal {
 public:
};

TopicResponsePb::TopicResponsePb(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyRpc.TopicResponsePb)
}
TopicResponsePb::TopicResponsePb(const TopicResponsePb& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  rcode_ = from.rcode_;
  // @@protoc_insertion_point(copy_constructor:MyRpc.TopicResponsePb)
}

void TopicResponsePb::SharedCtor() {
  rcode_ = 0;
}

TopicResponsePb::~TopicResponsePb() {
  // @@protoc_insertion_point(destructor:MyRpc.TopicResponsePb)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void TopicResponsePb::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void TopicResponsePb::ArenaDtor(void* object) {
  TopicResponsePb* _this = reinterpret_cast< TopicResponsePb* >(object);
  (void)_this;
}
void TopicResponsePb::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TopicResponsePb::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TopicResponsePb& TopicResponsePb::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_TopicResponsePb_message_2eproto.base);
  return *internal_default_instance();
}


void TopicResponsePb::Clear() {
// @@protoc_insertion_point(message_clear_start:MyRpc.TopicResponsePb)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  rcode_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TopicResponsePb::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 rcode = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          rcode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* TopicResponsePb::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MyRpc.TopicResponsePb)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 rcode = 1;
  if (this->rcode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_rcode(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyRpc.TopicResponsePb)
  return target;
}

size_t TopicResponsePb::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyRpc.TopicResponsePb)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 rcode = 1;
  if (this->rcode() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_rcode());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TopicResponsePb::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MyRpc.TopicResponsePb)
  GOOGLE_DCHECK_NE(&from, this);
  const TopicResponsePb* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<TopicResponsePb>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MyRpc.TopicResponsePb)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MyRpc.TopicResponsePb)
    MergeFrom(*source);
  }
}

void TopicResponsePb::MergeFrom(const TopicResponsePb& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MyRpc.TopicResponsePb)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.rcode() != 0) {
    _internal_set_rcode(from._internal_rcode());
  }
}

void TopicResponsePb::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MyRpc.TopicResponsePb)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TopicResponsePb::CopyFrom(const TopicResponsePb& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyRpc.TopicResponsePb)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TopicResponsePb::IsInitialized() const {
  return true;
}

void TopicResponsePb::InternalSwap(TopicResponsePb* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(rcode_, other->rcode_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TopicResponsePb::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ServiceRequestPb::InitAsDefaultInstance() {
  ::MyRpc::_ServiceRequestPb_default_instance_._instance.get_mutable()->host_ = const_cast< ::MyRpc::Host*>(
      ::MyRpc::Host::internal_default_instance());
}
class ServiceRequestPb::_Internal {
 public:
  static const ::MyRpc::Host& host(const ServiceRequestPb* msg);
};

const ::MyRpc::Host&
ServiceRequestPb::_Internal::host(const ServiceRequestPb* msg) {
  return *msg->host_;
}
ServiceRequestPb::ServiceRequestPb(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyRpc.ServiceRequestPb)
}
ServiceRequestPb::ServiceRequestPb(const ServiceRequestPb& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  method_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_method().empty()) {
    method_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_method(),
      GetArena());
  }
  if (from._internal_has_host()) {
    host_ = new ::MyRpc::Host(*from.host_);
  } else {
    host_ = nullptr;
  }
  optype_ = from.optype_;
  // @@protoc_insertion_point(copy_constructor:MyRpc.ServiceRequestPb)
}

void ServiceRequestPb::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ServiceRequestPb_message_2eproto.base);
  method_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&host_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&optype_) -
      reinterpret_cast<char*>(&host_)) + sizeof(optype_));
}

ServiceRequestPb::~ServiceRequestPb() {
  // @@protoc_insertion_point(destructor:MyRpc.ServiceRequestPb)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ServiceRequestPb::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  method_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete host_;
}

void ServiceRequestPb::ArenaDtor(void* object) {
  ServiceRequestPb* _this = reinterpret_cast< ServiceRequestPb* >(object);
  (void)_this;
}
void ServiceRequestPb::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ServiceRequestPb::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ServiceRequestPb& ServiceRequestPb::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ServiceRequestPb_message_2eproto.base);
  return *internal_default_instance();
}


void ServiceRequestPb::Clear() {
// @@protoc_insertion_point(message_clear_start:MyRpc.ServiceRequestPb)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  method_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  if (GetArena() == nullptr && host_ != nullptr) {
    delete host_;
  }
  host_ = nullptr;
  optype_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ServiceRequestPb::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string method = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_method();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "MyRpc.ServiceRequestPb.method"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 optype = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          optype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .MyRpc.Host host = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_host(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ServiceRequestPb::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MyRpc.ServiceRequestPb)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string method = 1;
  if (this->method().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_method().data(), static_cast<int>(this->_internal_method().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "MyRpc.ServiceRequestPb.method");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_method(), target);
  }

  // int32 optype = 2;
  if (this->optype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_optype(), target);
  }

  // .MyRpc.Host host = 3;
  if (this->has_host()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::host(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyRpc.ServiceRequestPb)
  return target;
}

size_t ServiceRequestPb::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyRpc.ServiceRequestPb)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string method = 1;
  if (this->method().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_method());
  }

  // .MyRpc.Host host = 3;
  if (this->has_host()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *host_);
  }

  // int32 optype = 2;
  if (this->optype() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_optype());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ServiceRequestPb::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MyRpc.ServiceRequestPb)
  GOOGLE_DCHECK_NE(&from, this);
  const ServiceRequestPb* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ServiceRequestPb>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MyRpc.ServiceRequestPb)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MyRpc.ServiceRequestPb)
    MergeFrom(*source);
  }
}

void ServiceRequestPb::MergeFrom(const ServiceRequestPb& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MyRpc.ServiceRequestPb)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.method().size() > 0) {
    _internal_set_method(from._internal_method());
  }
  if (from.has_host()) {
    _internal_mutable_host()->::MyRpc::Host::MergeFrom(from._internal_host());
  }
  if (from.optype() != 0) {
    _internal_set_optype(from._internal_optype());
  }
}

void ServiceRequestPb::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MyRpc.ServiceRequestPb)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ServiceRequestPb::CopyFrom(const ServiceRequestPb& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyRpc.ServiceRequestPb)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ServiceRequestPb::IsInitialized() const {
  return true;
}

void ServiceRequestPb::InternalSwap(ServiceRequestPb* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  method_.Swap(&other->method_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ServiceRequestPb, optype_)
      + sizeof(ServiceRequestPb::optype_)
      - PROTOBUF_FIELD_OFFSET(ServiceRequestPb, host_)>(
          reinterpret_cast<char*>(&host_),
          reinterpret_cast<char*>(&other->host_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ServiceRequestPb::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ServiceResponsePb::InitAsDefaultInstance() {
}
class ServiceResponsePb::_Internal {
 public:
};

ServiceResponsePb::ServiceResponsePb(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  hosts_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyRpc.ServiceResponsePb)
}
ServiceResponsePb::ServiceResponsePb(const ServiceResponsePb& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      hosts_(from.hosts_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  method_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_method().empty()) {
    method_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_method(),
      GetArena());
  }
  ::memcpy(&rcode_, &from.rcode_,
    static_cast<size_t>(reinterpret_cast<char*>(&optype_) -
    reinterpret_cast<char*>(&rcode_)) + sizeof(optype_));
  // @@protoc_insertion_point(copy_constructor:MyRpc.ServiceResponsePb)
}

void ServiceResponsePb::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ServiceResponsePb_message_2eproto.base);
  method_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&rcode_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&optype_) -
      reinterpret_cast<char*>(&rcode_)) + sizeof(optype_));
}

ServiceResponsePb::~ServiceResponsePb() {
  // @@protoc_insertion_point(destructor:MyRpc.ServiceResponsePb)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ServiceResponsePb::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  method_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ServiceResponsePb::ArenaDtor(void* object) {
  ServiceResponsePb* _this = reinterpret_cast< ServiceResponsePb* >(object);
  (void)_this;
}
void ServiceResponsePb::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ServiceResponsePb::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ServiceResponsePb& ServiceResponsePb::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ServiceResponsePb_message_2eproto.base);
  return *internal_default_instance();
}


void ServiceResponsePb::Clear() {
// @@protoc_insertion_point(message_clear_start:MyRpc.ServiceResponsePb)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  hosts_.Clear();
  method_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&rcode_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&optype_) -
      reinterpret_cast<char*>(&rcode_)) + sizeof(optype_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ServiceResponsePb::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 rcode = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          rcode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 optype = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          optype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string method = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_method();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "MyRpc.ServiceResponsePb.method"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .MyRpc.Host hosts = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_hosts(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ServiceResponsePb::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MyRpc.ServiceResponsePb)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 rcode = 1;
  if (this->rcode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_rcode(), target);
  }

  // int32 optype = 2;
  if (this->optype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_optype(), target);
  }

  // string method = 3;
  if (this->method().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_method().data(), static_cast<int>(this->_internal_method().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "MyRpc.ServiceResponsePb.method");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_method(), target);
  }

  // repeated .MyRpc.Host hosts = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_hosts_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_hosts(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyRpc.ServiceResponsePb)
  return target;
}

size_t ServiceResponsePb::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyRpc.ServiceResponsePb)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .MyRpc.Host hosts = 4;
  total_size += 1UL * this->_internal_hosts_size();
  for (const auto& msg : this->hosts_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string method = 3;
  if (this->method().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_method());
  }

  // int32 rcode = 1;
  if (this->rcode() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_rcode());
  }

  // int32 optype = 2;
  if (this->optype() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_optype());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ServiceResponsePb::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MyRpc.ServiceResponsePb)
  GOOGLE_DCHECK_NE(&from, this);
  const ServiceResponsePb* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ServiceResponsePb>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MyRpc.ServiceResponsePb)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MyRpc.ServiceResponsePb)
    MergeFrom(*source);
  }
}

void ServiceResponsePb::MergeFrom(const ServiceResponsePb& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MyRpc.ServiceResponsePb)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  hosts_.MergeFrom(from.hosts_);
  if (from.method().size() > 0) {
    _internal_set_method(from._internal_method());
  }
  if (from.rcode() != 0) {
    _internal_set_rcode(from._internal_rcode());
  }
  if (from.optype() != 0) {
    _internal_set_optype(from._internal_optype());
  }
}

void ServiceResponsePb::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MyRpc.ServiceResponsePb)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ServiceResponsePb::CopyFrom(const ServiceResponsePb& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyRpc.ServiceResponsePb)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ServiceResponsePb::IsInitialized() const {
  return true;
}

void ServiceResponsePb::InternalSwap(ServiceResponsePb* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  hosts_.InternalSwap(&other->hosts_);
  method_.Swap(&other->method_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ServiceResponsePb, optype_)
      + sizeof(ServiceResponsePb::optype_)
      - PROTOBUF_FIELD_OFFSET(ServiceResponsePb, rcode_)>(
          reinterpret_cast<char*>(&rcode_),
          reinterpret_cast<char*>(&other->rcode_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ServiceResponsePb::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace MyRpc
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::MyRpc::Host* Arena::CreateMaybeMessage< ::MyRpc::Host >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MyRpc::Host >(arena);
}
template<> PROTOBUF_NOINLINE ::MyRpc::RpcRequestPb* Arena::CreateMaybeMessage< ::MyRpc::RpcRequestPb >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MyRpc::RpcRequestPb >(arena);
}
template<> PROTOBUF_NOINLINE ::MyRpc::RpcResponsePb* Arena::CreateMaybeMessage< ::MyRpc::RpcResponsePb >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MyRpc::RpcResponsePb >(arena);
}
template<> PROTOBUF_NOINLINE ::MyRpc::TopicRequestPb* Arena::CreateMaybeMessage< ::MyRpc::TopicRequestPb >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MyRpc::TopicRequestPb >(arena);
}
template<> PROTOBUF_NOINLINE ::MyRpc::TopicResponsePb* Arena::CreateMaybeMessage< ::MyRpc::TopicResponsePb >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MyRpc::TopicResponsePb >(arena);
}
template<> PROTOBUF_NOINLINE ::MyRpc::ServiceRequestPb* Arena::CreateMaybeMessage< ::MyRpc::ServiceRequestPb >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MyRpc::ServiceRequestPb >(arena);
}
template<> PROTOBUF_NOINLINE ::MyRpc::ServiceResponsePb* Arena::CreateMaybeMessage< ::MyRpc::ServiceResponsePb >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MyRpc::ServiceResponsePb >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
