// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_message_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_message_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/struct.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_message_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[7]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2eproto;
namespace MyRpc {
class Host;
class HostDefaultTypeInternal;
extern HostDefaultTypeInternal _Host_default_instance_;
class RpcRequestPb;
class RpcRequestPbDefaultTypeInternal;
extern RpcRequestPbDefaultTypeInternal _RpcRequestPb_default_instance_;
class RpcResponsePb;
class RpcResponsePbDefaultTypeInternal;
extern RpcResponsePbDefaultTypeInternal _RpcResponsePb_default_instance_;
class ServiceRequestPb;
class ServiceRequestPbDefaultTypeInternal;
extern ServiceRequestPbDefaultTypeInternal _ServiceRequestPb_default_instance_;
class ServiceResponsePb;
class ServiceResponsePbDefaultTypeInternal;
extern ServiceResponsePbDefaultTypeInternal _ServiceResponsePb_default_instance_;
class TopicRequestPb;
class TopicRequestPbDefaultTypeInternal;
extern TopicRequestPbDefaultTypeInternal _TopicRequestPb_default_instance_;
class TopicResponsePb;
class TopicResponsePbDefaultTypeInternal;
extern TopicResponsePbDefaultTypeInternal _TopicResponsePb_default_instance_;
}  // namespace MyRpc
PROTOBUF_NAMESPACE_OPEN
template<> ::MyRpc::Host* Arena::CreateMaybeMessage<::MyRpc::Host>(Arena*);
template<> ::MyRpc::RpcRequestPb* Arena::CreateMaybeMessage<::MyRpc::RpcRequestPb>(Arena*);
template<> ::MyRpc::RpcResponsePb* Arena::CreateMaybeMessage<::MyRpc::RpcResponsePb>(Arena*);
template<> ::MyRpc::ServiceRequestPb* Arena::CreateMaybeMessage<::MyRpc::ServiceRequestPb>(Arena*);
template<> ::MyRpc::ServiceResponsePb* Arena::CreateMaybeMessage<::MyRpc::ServiceResponsePb>(Arena*);
template<> ::MyRpc::TopicRequestPb* Arena::CreateMaybeMessage<::MyRpc::TopicRequestPb>(Arena*);
template<> ::MyRpc::TopicResponsePb* Arena::CreateMaybeMessage<::MyRpc::TopicResponsePb>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace MyRpc {

enum Mtype : int {
  REQ_RPC = 0,
  REQ_SERVICE = 1,
  REQ_TOPIC = 2,
  RSP_RPC = 3,
  RSP_TOPIC = 4,
  RSP_SERVICE = 5,
  Mtype_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Mtype_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Mtype_IsValid(int value);
constexpr Mtype Mtype_MIN = REQ_RPC;
constexpr Mtype Mtype_MAX = RSP_SERVICE;
constexpr int Mtype_ARRAYSIZE = Mtype_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Mtype_descriptor();
template<typename T>
inline const std::string& Mtype_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Mtype>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Mtype_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Mtype_descriptor(), enum_t_value);
}
inline bool Mtype_Parse(
    const std::string& name, Mtype* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Mtype>(
    Mtype_descriptor(), name, value);
}
enum Rcode : int {
  RCODE_OK = 0,
  RCODE_PARSE_FAILED = 1,
  RCODE_ERROR_MSGTYPE = 2,
  RCODE_INVALID_MSG = 3,
  RCODE_DISCONNECTED = 4,
  RCODE_INVALID_PARAMS = 5,
  RCODE_NOT_FOUND_SERVICE = 6,
  RCODE_INVALID_OPTYPE = 7,
  RCODE_NOT_FOUND_TOPIC = 8,
  RCODE_INTERNAL_ERROR = 9,
  RCODE_INVALID_RESULT = 10,
  Rcode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Rcode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Rcode_IsValid(int value);
constexpr Rcode Rcode_MIN = RCODE_OK;
constexpr Rcode Rcode_MAX = RCODE_INVALID_RESULT;
constexpr int Rcode_ARRAYSIZE = Rcode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Rcode_descriptor();
template<typename T>
inline const std::string& Rcode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Rcode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Rcode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Rcode_descriptor(), enum_t_value);
}
inline bool Rcode_Parse(
    const std::string& name, Rcode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Rcode>(
    Rcode_descriptor(), name, value);
}
enum TopicOptype : int {
  TOPIC_CREATE = 0,
  TOPIC_REMOVE = 1,
  TOPIC_SUBSCRIBE = 2,
  TOPIC_CANCEL = 3,
  TOPIC_PUBLISH = 4,
  SERVICE_UNKNOW = 5,
  TopicOptype_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  TopicOptype_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool TopicOptype_IsValid(int value);
constexpr TopicOptype TopicOptype_MIN = TOPIC_CREATE;
constexpr TopicOptype TopicOptype_MAX = SERVICE_UNKNOW;
constexpr int TopicOptype_ARRAYSIZE = TopicOptype_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TopicOptype_descriptor();
template<typename T>
inline const std::string& TopicOptype_Name(T enum_t_value) {
  static_assert(::std::is_same<T, TopicOptype>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function TopicOptype_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    TopicOptype_descriptor(), enum_t_value);
}
inline bool TopicOptype_Parse(
    const std::string& name, TopicOptype* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<TopicOptype>(
    TopicOptype_descriptor(), name, value);
}
enum ServiceOptype : int {
  SERVICE_REGISTRY = 0,
  SERVICE_DISCOVERY = 1,
  SERVICE_ONLINE = 2,
  SERVICE_OFFLINE = 3,
  SERVICE_UNKNOW_PB = 4,
  ServiceOptype_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ServiceOptype_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ServiceOptype_IsValid(int value);
constexpr ServiceOptype ServiceOptype_MIN = SERVICE_REGISTRY;
constexpr ServiceOptype ServiceOptype_MAX = SERVICE_UNKNOW_PB;
constexpr int ServiceOptype_ARRAYSIZE = ServiceOptype_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ServiceOptype_descriptor();
template<typename T>
inline const std::string& ServiceOptype_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ServiceOptype>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ServiceOptype_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ServiceOptype_descriptor(), enum_t_value);
}
inline bool ServiceOptype_Parse(
    const std::string& name, ServiceOptype* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ServiceOptype>(
    ServiceOptype_descriptor(), name, value);
}
// ===================================================================

class Host PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MyRpc.Host) */ {
 public:
  inline Host() : Host(nullptr) {};
  virtual ~Host();

  Host(const Host& from);
  Host(Host&& from) noexcept
    : Host() {
    *this = ::std::move(from);
  }

  inline Host& operator=(const Host& from) {
    CopyFrom(from);
    return *this;
  }
  inline Host& operator=(Host&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Host& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Host* internal_default_instance() {
    return reinterpret_cast<const Host*>(
               &_Host_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Host& a, Host& b) {
    a.Swap(&b);
  }
  inline void Swap(Host* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Host* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Host* New() const final {
    return CreateMaybeMessage<Host>(nullptr);
  }

  Host* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Host>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Host& from);
  void MergeFrom(const Host& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Host* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MyRpc.Host";
  }
  protected:
  explicit Host(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIpFieldNumber = 1,
    kPortFieldNumber = 2,
  };
  // string ip = 1;
  void clear_ip();
  const std::string& ip() const;
  void set_ip(const std::string& value);
  void set_ip(std::string&& value);
  void set_ip(const char* value);
  void set_ip(const char* value, size_t size);
  std::string* mutable_ip();
  std::string* release_ip();
  void set_allocated_ip(std::string* ip);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_ip();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_ip(
      std::string* ip);
  private:
  const std::string& _internal_ip() const;
  void _internal_set_ip(const std::string& value);
  std::string* _internal_mutable_ip();
  public:

  // int32 port = 2;
  void clear_port();
  ::PROTOBUF_NAMESPACE_ID::int32 port() const;
  void set_port(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_port() const;
  void _internal_set_port(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:MyRpc.Host)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_;
  ::PROTOBUF_NAMESPACE_ID::int32 port_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class RpcRequestPb PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MyRpc.RpcRequestPb) */ {
 public:
  inline RpcRequestPb() : RpcRequestPb(nullptr) {};
  virtual ~RpcRequestPb();

  RpcRequestPb(const RpcRequestPb& from);
  RpcRequestPb(RpcRequestPb&& from) noexcept
    : RpcRequestPb() {
    *this = ::std::move(from);
  }

  inline RpcRequestPb& operator=(const RpcRequestPb& from) {
    CopyFrom(from);
    return *this;
  }
  inline RpcRequestPb& operator=(RpcRequestPb&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RpcRequestPb& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RpcRequestPb* internal_default_instance() {
    return reinterpret_cast<const RpcRequestPb*>(
               &_RpcRequestPb_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RpcRequestPb& a, RpcRequestPb& b) {
    a.Swap(&b);
  }
  inline void Swap(RpcRequestPb* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RpcRequestPb* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RpcRequestPb* New() const final {
    return CreateMaybeMessage<RpcRequestPb>(nullptr);
  }

  RpcRequestPb* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RpcRequestPb>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RpcRequestPb& from);
  void MergeFrom(const RpcRequestPb& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RpcRequestPb* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MyRpc.RpcRequestPb";
  }
  protected:
  explicit RpcRequestPb(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMethodFieldNumber = 1,
    kParametersFieldNumber = 2,
  };
  // string method = 1;
  void clear_method();
  const std::string& method() const;
  void set_method(const std::string& value);
  void set_method(std::string&& value);
  void set_method(const char* value);
  void set_method(const char* value, size_t size);
  std::string* mutable_method();
  std::string* release_method();
  void set_allocated_method(std::string* method);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_method();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_method(
      std::string* method);
  private:
  const std::string& _internal_method() const;
  void _internal_set_method(const std::string& value);
  std::string* _internal_mutable_method();
  public:

  // .google.protobuf.Struct parameters = 2;
  bool has_parameters() const;
  private:
  bool _internal_has_parameters() const;
  public:
  void clear_parameters();
  const PROTOBUF_NAMESPACE_ID::Struct& parameters() const;
  PROTOBUF_NAMESPACE_ID::Struct* release_parameters();
  PROTOBUF_NAMESPACE_ID::Struct* mutable_parameters();
  void set_allocated_parameters(PROTOBUF_NAMESPACE_ID::Struct* parameters);
  private:
  const PROTOBUF_NAMESPACE_ID::Struct& _internal_parameters() const;
  PROTOBUF_NAMESPACE_ID::Struct* _internal_mutable_parameters();
  public:
  void unsafe_arena_set_allocated_parameters(
      PROTOBUF_NAMESPACE_ID::Struct* parameters);
  PROTOBUF_NAMESPACE_ID::Struct* unsafe_arena_release_parameters();

  // @@protoc_insertion_point(class_scope:MyRpc.RpcRequestPb)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr method_;
  PROTOBUF_NAMESPACE_ID::Struct* parameters_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class RpcResponsePb PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MyRpc.RpcResponsePb) */ {
 public:
  inline RpcResponsePb() : RpcResponsePb(nullptr) {};
  virtual ~RpcResponsePb();

  RpcResponsePb(const RpcResponsePb& from);
  RpcResponsePb(RpcResponsePb&& from) noexcept
    : RpcResponsePb() {
    *this = ::std::move(from);
  }

  inline RpcResponsePb& operator=(const RpcResponsePb& from) {
    CopyFrom(from);
    return *this;
  }
  inline RpcResponsePb& operator=(RpcResponsePb&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RpcResponsePb& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RpcResponsePb* internal_default_instance() {
    return reinterpret_cast<const RpcResponsePb*>(
               &_RpcResponsePb_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(RpcResponsePb& a, RpcResponsePb& b) {
    a.Swap(&b);
  }
  inline void Swap(RpcResponsePb* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RpcResponsePb* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RpcResponsePb* New() const final {
    return CreateMaybeMessage<RpcResponsePb>(nullptr);
  }

  RpcResponsePb* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RpcResponsePb>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RpcResponsePb& from);
  void MergeFrom(const RpcResponsePb& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RpcResponsePb* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MyRpc.RpcResponsePb";
  }
  protected:
  explicit RpcResponsePb(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 2,
    kRcodeFieldNumber = 1,
  };
  // .google.protobuf.Value result = 2;
  bool has_result() const;
  private:
  bool _internal_has_result() const;
  public:
  void clear_result();
  const PROTOBUF_NAMESPACE_ID::Value& result() const;
  PROTOBUF_NAMESPACE_ID::Value* release_result();
  PROTOBUF_NAMESPACE_ID::Value* mutable_result();
  void set_allocated_result(PROTOBUF_NAMESPACE_ID::Value* result);
  private:
  const PROTOBUF_NAMESPACE_ID::Value& _internal_result() const;
  PROTOBUF_NAMESPACE_ID::Value* _internal_mutable_result();
  public:
  void unsafe_arena_set_allocated_result(
      PROTOBUF_NAMESPACE_ID::Value* result);
  PROTOBUF_NAMESPACE_ID::Value* unsafe_arena_release_result();

  // int32 rcode = 1;
  void clear_rcode();
  ::PROTOBUF_NAMESPACE_ID::int32 rcode() const;
  void set_rcode(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_rcode() const;
  void _internal_set_rcode(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:MyRpc.RpcResponsePb)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  PROTOBUF_NAMESPACE_ID::Value* result_;
  ::PROTOBUF_NAMESPACE_ID::int32 rcode_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class TopicRequestPb PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MyRpc.TopicRequestPb) */ {
 public:
  inline TopicRequestPb() : TopicRequestPb(nullptr) {};
  virtual ~TopicRequestPb();

  TopicRequestPb(const TopicRequestPb& from);
  TopicRequestPb(TopicRequestPb&& from) noexcept
    : TopicRequestPb() {
    *this = ::std::move(from);
  }

  inline TopicRequestPb& operator=(const TopicRequestPb& from) {
    CopyFrom(from);
    return *this;
  }
  inline TopicRequestPb& operator=(TopicRequestPb&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TopicRequestPb& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TopicRequestPb* internal_default_instance() {
    return reinterpret_cast<const TopicRequestPb*>(
               &_TopicRequestPb_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(TopicRequestPb& a, TopicRequestPb& b) {
    a.Swap(&b);
  }
  inline void Swap(TopicRequestPb* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TopicRequestPb* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TopicRequestPb* New() const final {
    return CreateMaybeMessage<TopicRequestPb>(nullptr);
  }

  TopicRequestPb* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TopicRequestPb>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TopicRequestPb& from);
  void MergeFrom(const TopicRequestPb& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TopicRequestPb* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MyRpc.TopicRequestPb";
  }
  protected:
  explicit TopicRequestPb(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTopicKeyFieldNumber = 1,
    kTopicMsgFieldNumber = 3,
    kOptypeFieldNumber = 2,
  };
  // string topic_key = 1;
  void clear_topic_key();
  const std::string& topic_key() const;
  void set_topic_key(const std::string& value);
  void set_topic_key(std::string&& value);
  void set_topic_key(const char* value);
  void set_topic_key(const char* value, size_t size);
  std::string* mutable_topic_key();
  std::string* release_topic_key();
  void set_allocated_topic_key(std::string* topic_key);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_topic_key();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_topic_key(
      std::string* topic_key);
  private:
  const std::string& _internal_topic_key() const;
  void _internal_set_topic_key(const std::string& value);
  std::string* _internal_mutable_topic_key();
  public:

  // string topic_msg = 3;
  void clear_topic_msg();
  const std::string& topic_msg() const;
  void set_topic_msg(const std::string& value);
  void set_topic_msg(std::string&& value);
  void set_topic_msg(const char* value);
  void set_topic_msg(const char* value, size_t size);
  std::string* mutable_topic_msg();
  std::string* release_topic_msg();
  void set_allocated_topic_msg(std::string* topic_msg);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_topic_msg();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_topic_msg(
      std::string* topic_msg);
  private:
  const std::string& _internal_topic_msg() const;
  void _internal_set_topic_msg(const std::string& value);
  std::string* _internal_mutable_topic_msg();
  public:

  // int32 optype = 2;
  void clear_optype();
  ::PROTOBUF_NAMESPACE_ID::int32 optype() const;
  void set_optype(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_optype() const;
  void _internal_set_optype(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:MyRpc.TopicRequestPb)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr topic_key_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr topic_msg_;
  ::PROTOBUF_NAMESPACE_ID::int32 optype_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class TopicResponsePb PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MyRpc.TopicResponsePb) */ {
 public:
  inline TopicResponsePb() : TopicResponsePb(nullptr) {};
  virtual ~TopicResponsePb();

  TopicResponsePb(const TopicResponsePb& from);
  TopicResponsePb(TopicResponsePb&& from) noexcept
    : TopicResponsePb() {
    *this = ::std::move(from);
  }

  inline TopicResponsePb& operator=(const TopicResponsePb& from) {
    CopyFrom(from);
    return *this;
  }
  inline TopicResponsePb& operator=(TopicResponsePb&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TopicResponsePb& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TopicResponsePb* internal_default_instance() {
    return reinterpret_cast<const TopicResponsePb*>(
               &_TopicResponsePb_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(TopicResponsePb& a, TopicResponsePb& b) {
    a.Swap(&b);
  }
  inline void Swap(TopicResponsePb* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TopicResponsePb* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TopicResponsePb* New() const final {
    return CreateMaybeMessage<TopicResponsePb>(nullptr);
  }

  TopicResponsePb* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TopicResponsePb>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TopicResponsePb& from);
  void MergeFrom(const TopicResponsePb& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TopicResponsePb* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MyRpc.TopicResponsePb";
  }
  protected:
  explicit TopicResponsePb(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRcodeFieldNumber = 1,
  };
  // int32 rcode = 1;
  void clear_rcode();
  ::PROTOBUF_NAMESPACE_ID::int32 rcode() const;
  void set_rcode(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_rcode() const;
  void _internal_set_rcode(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:MyRpc.TopicResponsePb)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 rcode_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class ServiceRequestPb PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MyRpc.ServiceRequestPb) */ {
 public:
  inline ServiceRequestPb() : ServiceRequestPb(nullptr) {};
  virtual ~ServiceRequestPb();

  ServiceRequestPb(const ServiceRequestPb& from);
  ServiceRequestPb(ServiceRequestPb&& from) noexcept
    : ServiceRequestPb() {
    *this = ::std::move(from);
  }

  inline ServiceRequestPb& operator=(const ServiceRequestPb& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServiceRequestPb& operator=(ServiceRequestPb&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ServiceRequestPb& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServiceRequestPb* internal_default_instance() {
    return reinterpret_cast<const ServiceRequestPb*>(
               &_ServiceRequestPb_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(ServiceRequestPb& a, ServiceRequestPb& b) {
    a.Swap(&b);
  }
  inline void Swap(ServiceRequestPb* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServiceRequestPb* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ServiceRequestPb* New() const final {
    return CreateMaybeMessage<ServiceRequestPb>(nullptr);
  }

  ServiceRequestPb* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ServiceRequestPb>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ServiceRequestPb& from);
  void MergeFrom(const ServiceRequestPb& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServiceRequestPb* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MyRpc.ServiceRequestPb";
  }
  protected:
  explicit ServiceRequestPb(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMethodFieldNumber = 1,
    kHostFieldNumber = 3,
    kOptypeFieldNumber = 2,
  };
  // string method = 1;
  void clear_method();
  const std::string& method() const;
  void set_method(const std::string& value);
  void set_method(std::string&& value);
  void set_method(const char* value);
  void set_method(const char* value, size_t size);
  std::string* mutable_method();
  std::string* release_method();
  void set_allocated_method(std::string* method);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_method();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_method(
      std::string* method);
  private:
  const std::string& _internal_method() const;
  void _internal_set_method(const std::string& value);
  std::string* _internal_mutable_method();
  public:

  // .MyRpc.Host host = 3;
  bool has_host() const;
  private:
  bool _internal_has_host() const;
  public:
  void clear_host();
  const ::MyRpc::Host& host() const;
  ::MyRpc::Host* release_host();
  ::MyRpc::Host* mutable_host();
  void set_allocated_host(::MyRpc::Host* host);
  private:
  const ::MyRpc::Host& _internal_host() const;
  ::MyRpc::Host* _internal_mutable_host();
  public:
  void unsafe_arena_set_allocated_host(
      ::MyRpc::Host* host);
  ::MyRpc::Host* unsafe_arena_release_host();

  // int32 optype = 2;
  void clear_optype();
  ::PROTOBUF_NAMESPACE_ID::int32 optype() const;
  void set_optype(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_optype() const;
  void _internal_set_optype(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:MyRpc.ServiceRequestPb)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr method_;
  ::MyRpc::Host* host_;
  ::PROTOBUF_NAMESPACE_ID::int32 optype_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class ServiceResponsePb PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MyRpc.ServiceResponsePb) */ {
 public:
  inline ServiceResponsePb() : ServiceResponsePb(nullptr) {};
  virtual ~ServiceResponsePb();

  ServiceResponsePb(const ServiceResponsePb& from);
  ServiceResponsePb(ServiceResponsePb&& from) noexcept
    : ServiceResponsePb() {
    *this = ::std::move(from);
  }

  inline ServiceResponsePb& operator=(const ServiceResponsePb& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServiceResponsePb& operator=(ServiceResponsePb&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ServiceResponsePb& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServiceResponsePb* internal_default_instance() {
    return reinterpret_cast<const ServiceResponsePb*>(
               &_ServiceResponsePb_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(ServiceResponsePb& a, ServiceResponsePb& b) {
    a.Swap(&b);
  }
  inline void Swap(ServiceResponsePb* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServiceResponsePb* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ServiceResponsePb* New() const final {
    return CreateMaybeMessage<ServiceResponsePb>(nullptr);
  }

  ServiceResponsePb* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ServiceResponsePb>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ServiceResponsePb& from);
  void MergeFrom(const ServiceResponsePb& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServiceResponsePb* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MyRpc.ServiceResponsePb";
  }
  protected:
  explicit ServiceResponsePb(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHostsFieldNumber = 4,
    kMethodFieldNumber = 3,
    kRcodeFieldNumber = 1,
    kOptypeFieldNumber = 2,
  };
  // repeated .MyRpc.Host hosts = 4;
  int hosts_size() const;
  private:
  int _internal_hosts_size() const;
  public:
  void clear_hosts();
  ::MyRpc::Host* mutable_hosts(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::MyRpc::Host >*
      mutable_hosts();
  private:
  const ::MyRpc::Host& _internal_hosts(int index) const;
  ::MyRpc::Host* _internal_add_hosts();
  public:
  const ::MyRpc::Host& hosts(int index) const;
  ::MyRpc::Host* add_hosts();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::MyRpc::Host >&
      hosts() const;

  // string method = 3;
  void clear_method();
  const std::string& method() const;
  void set_method(const std::string& value);
  void set_method(std::string&& value);
  void set_method(const char* value);
  void set_method(const char* value, size_t size);
  std::string* mutable_method();
  std::string* release_method();
  void set_allocated_method(std::string* method);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_method();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_method(
      std::string* method);
  private:
  const std::string& _internal_method() const;
  void _internal_set_method(const std::string& value);
  std::string* _internal_mutable_method();
  public:

  // int32 rcode = 1;
  void clear_rcode();
  ::PROTOBUF_NAMESPACE_ID::int32 rcode() const;
  void set_rcode(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_rcode() const;
  void _internal_set_rcode(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 optype = 2;
  void clear_optype();
  ::PROTOBUF_NAMESPACE_ID::int32 optype() const;
  void set_optype(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_optype() const;
  void _internal_set_optype(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:MyRpc.ServiceResponsePb)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::MyRpc::Host > hosts_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr method_;
  ::PROTOBUF_NAMESPACE_ID::int32 rcode_;
  ::PROTOBUF_NAMESPACE_ID::int32 optype_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Host

// string ip = 1;
inline void Host::clear_ip() {
  ip_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Host::ip() const {
  // @@protoc_insertion_point(field_get:MyRpc.Host.ip)
  return _internal_ip();
}
inline void Host::set_ip(const std::string& value) {
  _internal_set_ip(value);
  // @@protoc_insertion_point(field_set:MyRpc.Host.ip)
}
inline std::string* Host::mutable_ip() {
  // @@protoc_insertion_point(field_mutable:MyRpc.Host.ip)
  return _internal_mutable_ip();
}
inline const std::string& Host::_internal_ip() const {
  return ip_.Get();
}
inline void Host::_internal_set_ip(const std::string& value) {
  
  ip_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Host::set_ip(std::string&& value) {
  
  ip_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:MyRpc.Host.ip)
}
inline void Host::set_ip(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  ip_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:MyRpc.Host.ip)
}
inline void Host::set_ip(const char* value,
    size_t size) {
  
  ip_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:MyRpc.Host.ip)
}
inline std::string* Host::_internal_mutable_ip() {
  
  return ip_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Host::release_ip() {
  // @@protoc_insertion_point(field_release:MyRpc.Host.ip)
  return ip_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Host::set_allocated_ip(std::string* ip) {
  if (ip != nullptr) {
    
  } else {
    
  }
  ip_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ip,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:MyRpc.Host.ip)
}
inline std::string* Host::unsafe_arena_release_ip() {
  // @@protoc_insertion_point(field_unsafe_arena_release:MyRpc.Host.ip)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return ip_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Host::unsafe_arena_set_allocated_ip(
    std::string* ip) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (ip != nullptr) {
    
  } else {
    
  }
  ip_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ip, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:MyRpc.Host.ip)
}

// int32 port = 2;
inline void Host::clear_port() {
  port_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Host::_internal_port() const {
  return port_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Host::port() const {
  // @@protoc_insertion_point(field_get:MyRpc.Host.port)
  return _internal_port();
}
inline void Host::_internal_set_port(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  port_ = value;
}
inline void Host::set_port(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:MyRpc.Host.port)
}

// -------------------------------------------------------------------

// RpcRequestPb

// string method = 1;
inline void RpcRequestPb::clear_method() {
  method_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& RpcRequestPb::method() const {
  // @@protoc_insertion_point(field_get:MyRpc.RpcRequestPb.method)
  return _internal_method();
}
inline void RpcRequestPb::set_method(const std::string& value) {
  _internal_set_method(value);
  // @@protoc_insertion_point(field_set:MyRpc.RpcRequestPb.method)
}
inline std::string* RpcRequestPb::mutable_method() {
  // @@protoc_insertion_point(field_mutable:MyRpc.RpcRequestPb.method)
  return _internal_mutable_method();
}
inline const std::string& RpcRequestPb::_internal_method() const {
  return method_.Get();
}
inline void RpcRequestPb::_internal_set_method(const std::string& value) {
  
  method_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void RpcRequestPb::set_method(std::string&& value) {
  
  method_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:MyRpc.RpcRequestPb.method)
}
inline void RpcRequestPb::set_method(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  method_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:MyRpc.RpcRequestPb.method)
}
inline void RpcRequestPb::set_method(const char* value,
    size_t size) {
  
  method_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:MyRpc.RpcRequestPb.method)
}
inline std::string* RpcRequestPb::_internal_mutable_method() {
  
  return method_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* RpcRequestPb::release_method() {
  // @@protoc_insertion_point(field_release:MyRpc.RpcRequestPb.method)
  return method_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RpcRequestPb::set_allocated_method(std::string* method) {
  if (method != nullptr) {
    
  } else {
    
  }
  method_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), method,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:MyRpc.RpcRequestPb.method)
}
inline std::string* RpcRequestPb::unsafe_arena_release_method() {
  // @@protoc_insertion_point(field_unsafe_arena_release:MyRpc.RpcRequestPb.method)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return method_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void RpcRequestPb::unsafe_arena_set_allocated_method(
    std::string* method) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (method != nullptr) {
    
  } else {
    
  }
  method_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      method, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:MyRpc.RpcRequestPb.method)
}

// .google.protobuf.Struct parameters = 2;
inline bool RpcRequestPb::_internal_has_parameters() const {
  return this != internal_default_instance() && parameters_ != nullptr;
}
inline bool RpcRequestPb::has_parameters() const {
  return _internal_has_parameters();
}
inline const PROTOBUF_NAMESPACE_ID::Struct& RpcRequestPb::_internal_parameters() const {
  const PROTOBUF_NAMESPACE_ID::Struct* p = parameters_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Struct*>(
      &PROTOBUF_NAMESPACE_ID::_Struct_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Struct& RpcRequestPb::parameters() const {
  // @@protoc_insertion_point(field_get:MyRpc.RpcRequestPb.parameters)
  return _internal_parameters();
}
inline void RpcRequestPb::unsafe_arena_set_allocated_parameters(
    PROTOBUF_NAMESPACE_ID::Struct* parameters) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(parameters_);
  }
  parameters_ = parameters;
  if (parameters) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:MyRpc.RpcRequestPb.parameters)
}
inline PROTOBUF_NAMESPACE_ID::Struct* RpcRequestPb::release_parameters() {
  auto temp = unsafe_arena_release_parameters();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Struct* RpcRequestPb::unsafe_arena_release_parameters() {
  // @@protoc_insertion_point(field_release:MyRpc.RpcRequestPb.parameters)
  
  PROTOBUF_NAMESPACE_ID::Struct* temp = parameters_;
  parameters_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Struct* RpcRequestPb::_internal_mutable_parameters() {
  
  if (parameters_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Struct>(GetArena());
    parameters_ = p;
  }
  return parameters_;
}
inline PROTOBUF_NAMESPACE_ID::Struct* RpcRequestPb::mutable_parameters() {
  // @@protoc_insertion_point(field_mutable:MyRpc.RpcRequestPb.parameters)
  return _internal_mutable_parameters();
}
inline void RpcRequestPb::set_allocated_parameters(PROTOBUF_NAMESPACE_ID::Struct* parameters) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(parameters_);
  }
  if (parameters) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(parameters)->GetArena();
    if (message_arena != submessage_arena) {
      parameters = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, parameters, submessage_arena);
    }
    
  } else {
    
  }
  parameters_ = parameters;
  // @@protoc_insertion_point(field_set_allocated:MyRpc.RpcRequestPb.parameters)
}

// -------------------------------------------------------------------

// RpcResponsePb

// int32 rcode = 1;
inline void RpcResponsePb::clear_rcode() {
  rcode_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RpcResponsePb::_internal_rcode() const {
  return rcode_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RpcResponsePb::rcode() const {
  // @@protoc_insertion_point(field_get:MyRpc.RpcResponsePb.rcode)
  return _internal_rcode();
}
inline void RpcResponsePb::_internal_set_rcode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  rcode_ = value;
}
inline void RpcResponsePb::set_rcode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_rcode(value);
  // @@protoc_insertion_point(field_set:MyRpc.RpcResponsePb.rcode)
}

// .google.protobuf.Value result = 2;
inline bool RpcResponsePb::_internal_has_result() const {
  return this != internal_default_instance() && result_ != nullptr;
}
inline bool RpcResponsePb::has_result() const {
  return _internal_has_result();
}
inline const PROTOBUF_NAMESPACE_ID::Value& RpcResponsePb::_internal_result() const {
  const PROTOBUF_NAMESPACE_ID::Value* p = result_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Value*>(
      &PROTOBUF_NAMESPACE_ID::_Value_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Value& RpcResponsePb::result() const {
  // @@protoc_insertion_point(field_get:MyRpc.RpcResponsePb.result)
  return _internal_result();
}
inline void RpcResponsePb::unsafe_arena_set_allocated_result(
    PROTOBUF_NAMESPACE_ID::Value* result) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(result_);
  }
  result_ = result;
  if (result) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:MyRpc.RpcResponsePb.result)
}
inline PROTOBUF_NAMESPACE_ID::Value* RpcResponsePb::release_result() {
  auto temp = unsafe_arena_release_result();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Value* RpcResponsePb::unsafe_arena_release_result() {
  // @@protoc_insertion_point(field_release:MyRpc.RpcResponsePb.result)
  
  PROTOBUF_NAMESPACE_ID::Value* temp = result_;
  result_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Value* RpcResponsePb::_internal_mutable_result() {
  
  if (result_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Value>(GetArena());
    result_ = p;
  }
  return result_;
}
inline PROTOBUF_NAMESPACE_ID::Value* RpcResponsePb::mutable_result() {
  // @@protoc_insertion_point(field_mutable:MyRpc.RpcResponsePb.result)
  return _internal_mutable_result();
}
inline void RpcResponsePb::set_allocated_result(PROTOBUF_NAMESPACE_ID::Value* result) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(result_);
  }
  if (result) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(result)->GetArena();
    if (message_arena != submessage_arena) {
      result = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, result, submessage_arena);
    }
    
  } else {
    
  }
  result_ = result;
  // @@protoc_insertion_point(field_set_allocated:MyRpc.RpcResponsePb.result)
}

// -------------------------------------------------------------------

// TopicRequestPb

// string topic_key = 1;
inline void TopicRequestPb::clear_topic_key() {
  topic_key_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& TopicRequestPb::topic_key() const {
  // @@protoc_insertion_point(field_get:MyRpc.TopicRequestPb.topic_key)
  return _internal_topic_key();
}
inline void TopicRequestPb::set_topic_key(const std::string& value) {
  _internal_set_topic_key(value);
  // @@protoc_insertion_point(field_set:MyRpc.TopicRequestPb.topic_key)
}
inline std::string* TopicRequestPb::mutable_topic_key() {
  // @@protoc_insertion_point(field_mutable:MyRpc.TopicRequestPb.topic_key)
  return _internal_mutable_topic_key();
}
inline const std::string& TopicRequestPb::_internal_topic_key() const {
  return topic_key_.Get();
}
inline void TopicRequestPb::_internal_set_topic_key(const std::string& value) {
  
  topic_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void TopicRequestPb::set_topic_key(std::string&& value) {
  
  topic_key_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:MyRpc.TopicRequestPb.topic_key)
}
inline void TopicRequestPb::set_topic_key(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  topic_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:MyRpc.TopicRequestPb.topic_key)
}
inline void TopicRequestPb::set_topic_key(const char* value,
    size_t size) {
  
  topic_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:MyRpc.TopicRequestPb.topic_key)
}
inline std::string* TopicRequestPb::_internal_mutable_topic_key() {
  
  return topic_key_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* TopicRequestPb::release_topic_key() {
  // @@protoc_insertion_point(field_release:MyRpc.TopicRequestPb.topic_key)
  return topic_key_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TopicRequestPb::set_allocated_topic_key(std::string* topic_key) {
  if (topic_key != nullptr) {
    
  } else {
    
  }
  topic_key_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), topic_key,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:MyRpc.TopicRequestPb.topic_key)
}
inline std::string* TopicRequestPb::unsafe_arena_release_topic_key() {
  // @@protoc_insertion_point(field_unsafe_arena_release:MyRpc.TopicRequestPb.topic_key)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return topic_key_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void TopicRequestPb::unsafe_arena_set_allocated_topic_key(
    std::string* topic_key) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (topic_key != nullptr) {
    
  } else {
    
  }
  topic_key_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      topic_key, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:MyRpc.TopicRequestPb.topic_key)
}

// int32 optype = 2;
inline void TopicRequestPb::clear_optype() {
  optype_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TopicRequestPb::_internal_optype() const {
  return optype_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TopicRequestPb::optype() const {
  // @@protoc_insertion_point(field_get:MyRpc.TopicRequestPb.optype)
  return _internal_optype();
}
inline void TopicRequestPb::_internal_set_optype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  optype_ = value;
}
inline void TopicRequestPb::set_optype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_optype(value);
  // @@protoc_insertion_point(field_set:MyRpc.TopicRequestPb.optype)
}

// string topic_msg = 3;
inline void TopicRequestPb::clear_topic_msg() {
  topic_msg_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& TopicRequestPb::topic_msg() const {
  // @@protoc_insertion_point(field_get:MyRpc.TopicRequestPb.topic_msg)
  return _internal_topic_msg();
}
inline void TopicRequestPb::set_topic_msg(const std::string& value) {
  _internal_set_topic_msg(value);
  // @@protoc_insertion_point(field_set:MyRpc.TopicRequestPb.topic_msg)
}
inline std::string* TopicRequestPb::mutable_topic_msg() {
  // @@protoc_insertion_point(field_mutable:MyRpc.TopicRequestPb.topic_msg)
  return _internal_mutable_topic_msg();
}
inline const std::string& TopicRequestPb::_internal_topic_msg() const {
  return topic_msg_.Get();
}
inline void TopicRequestPb::_internal_set_topic_msg(const std::string& value) {
  
  topic_msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void TopicRequestPb::set_topic_msg(std::string&& value) {
  
  topic_msg_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:MyRpc.TopicRequestPb.topic_msg)
}
inline void TopicRequestPb::set_topic_msg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  topic_msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:MyRpc.TopicRequestPb.topic_msg)
}
inline void TopicRequestPb::set_topic_msg(const char* value,
    size_t size) {
  
  topic_msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:MyRpc.TopicRequestPb.topic_msg)
}
inline std::string* TopicRequestPb::_internal_mutable_topic_msg() {
  
  return topic_msg_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* TopicRequestPb::release_topic_msg() {
  // @@protoc_insertion_point(field_release:MyRpc.TopicRequestPb.topic_msg)
  return topic_msg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TopicRequestPb::set_allocated_topic_msg(std::string* topic_msg) {
  if (topic_msg != nullptr) {
    
  } else {
    
  }
  topic_msg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), topic_msg,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:MyRpc.TopicRequestPb.topic_msg)
}
inline std::string* TopicRequestPb::unsafe_arena_release_topic_msg() {
  // @@protoc_insertion_point(field_unsafe_arena_release:MyRpc.TopicRequestPb.topic_msg)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return topic_msg_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void TopicRequestPb::unsafe_arena_set_allocated_topic_msg(
    std::string* topic_msg) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (topic_msg != nullptr) {
    
  } else {
    
  }
  topic_msg_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      topic_msg, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:MyRpc.TopicRequestPb.topic_msg)
}

// -------------------------------------------------------------------

// TopicResponsePb

// int32 rcode = 1;
inline void TopicResponsePb::clear_rcode() {
  rcode_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TopicResponsePb::_internal_rcode() const {
  return rcode_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 TopicResponsePb::rcode() const {
  // @@protoc_insertion_point(field_get:MyRpc.TopicResponsePb.rcode)
  return _internal_rcode();
}
inline void TopicResponsePb::_internal_set_rcode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  rcode_ = value;
}
inline void TopicResponsePb::set_rcode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_rcode(value);
  // @@protoc_insertion_point(field_set:MyRpc.TopicResponsePb.rcode)
}

// -------------------------------------------------------------------

// ServiceRequestPb

// string method = 1;
inline void ServiceRequestPb::clear_method() {
  method_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ServiceRequestPb::method() const {
  // @@protoc_insertion_point(field_get:MyRpc.ServiceRequestPb.method)
  return _internal_method();
}
inline void ServiceRequestPb::set_method(const std::string& value) {
  _internal_set_method(value);
  // @@protoc_insertion_point(field_set:MyRpc.ServiceRequestPb.method)
}
inline std::string* ServiceRequestPb::mutable_method() {
  // @@protoc_insertion_point(field_mutable:MyRpc.ServiceRequestPb.method)
  return _internal_mutable_method();
}
inline const std::string& ServiceRequestPb::_internal_method() const {
  return method_.Get();
}
inline void ServiceRequestPb::_internal_set_method(const std::string& value) {
  
  method_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ServiceRequestPb::set_method(std::string&& value) {
  
  method_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:MyRpc.ServiceRequestPb.method)
}
inline void ServiceRequestPb::set_method(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  method_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:MyRpc.ServiceRequestPb.method)
}
inline void ServiceRequestPb::set_method(const char* value,
    size_t size) {
  
  method_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:MyRpc.ServiceRequestPb.method)
}
inline std::string* ServiceRequestPb::_internal_mutable_method() {
  
  return method_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ServiceRequestPb::release_method() {
  // @@protoc_insertion_point(field_release:MyRpc.ServiceRequestPb.method)
  return method_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ServiceRequestPb::set_allocated_method(std::string* method) {
  if (method != nullptr) {
    
  } else {
    
  }
  method_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), method,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:MyRpc.ServiceRequestPb.method)
}
inline std::string* ServiceRequestPb::unsafe_arena_release_method() {
  // @@protoc_insertion_point(field_unsafe_arena_release:MyRpc.ServiceRequestPb.method)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return method_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ServiceRequestPb::unsafe_arena_set_allocated_method(
    std::string* method) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (method != nullptr) {
    
  } else {
    
  }
  method_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      method, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:MyRpc.ServiceRequestPb.method)
}

// int32 optype = 2;
inline void ServiceRequestPb::clear_optype() {
  optype_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ServiceRequestPb::_internal_optype() const {
  return optype_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ServiceRequestPb::optype() const {
  // @@protoc_insertion_point(field_get:MyRpc.ServiceRequestPb.optype)
  return _internal_optype();
}
inline void ServiceRequestPb::_internal_set_optype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  optype_ = value;
}
inline void ServiceRequestPb::set_optype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_optype(value);
  // @@protoc_insertion_point(field_set:MyRpc.ServiceRequestPb.optype)
}

// .MyRpc.Host host = 3;
inline bool ServiceRequestPb::_internal_has_host() const {
  return this != internal_default_instance() && host_ != nullptr;
}
inline bool ServiceRequestPb::has_host() const {
  return _internal_has_host();
}
inline void ServiceRequestPb::clear_host() {
  if (GetArena() == nullptr && host_ != nullptr) {
    delete host_;
  }
  host_ = nullptr;
}
inline const ::MyRpc::Host& ServiceRequestPb::_internal_host() const {
  const ::MyRpc::Host* p = host_;
  return p != nullptr ? *p : *reinterpret_cast<const ::MyRpc::Host*>(
      &::MyRpc::_Host_default_instance_);
}
inline const ::MyRpc::Host& ServiceRequestPb::host() const {
  // @@protoc_insertion_point(field_get:MyRpc.ServiceRequestPb.host)
  return _internal_host();
}
inline void ServiceRequestPb::unsafe_arena_set_allocated_host(
    ::MyRpc::Host* host) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(host_);
  }
  host_ = host;
  if (host) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:MyRpc.ServiceRequestPb.host)
}
inline ::MyRpc::Host* ServiceRequestPb::release_host() {
  auto temp = unsafe_arena_release_host();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::MyRpc::Host* ServiceRequestPb::unsafe_arena_release_host() {
  // @@protoc_insertion_point(field_release:MyRpc.ServiceRequestPb.host)
  
  ::MyRpc::Host* temp = host_;
  host_ = nullptr;
  return temp;
}
inline ::MyRpc::Host* ServiceRequestPb::_internal_mutable_host() {
  
  if (host_ == nullptr) {
    auto* p = CreateMaybeMessage<::MyRpc::Host>(GetArena());
    host_ = p;
  }
  return host_;
}
inline ::MyRpc::Host* ServiceRequestPb::mutable_host() {
  // @@protoc_insertion_point(field_mutable:MyRpc.ServiceRequestPb.host)
  return _internal_mutable_host();
}
inline void ServiceRequestPb::set_allocated_host(::MyRpc::Host* host) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete host_;
  }
  if (host) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(host);
    if (message_arena != submessage_arena) {
      host = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, host, submessage_arena);
    }
    
  } else {
    
  }
  host_ = host;
  // @@protoc_insertion_point(field_set_allocated:MyRpc.ServiceRequestPb.host)
}

// -------------------------------------------------------------------

// ServiceResponsePb

// int32 rcode = 1;
inline void ServiceResponsePb::clear_rcode() {
  rcode_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ServiceResponsePb::_internal_rcode() const {
  return rcode_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ServiceResponsePb::rcode() const {
  // @@protoc_insertion_point(field_get:MyRpc.ServiceResponsePb.rcode)
  return _internal_rcode();
}
inline void ServiceResponsePb::_internal_set_rcode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  rcode_ = value;
}
inline void ServiceResponsePb::set_rcode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_rcode(value);
  // @@protoc_insertion_point(field_set:MyRpc.ServiceResponsePb.rcode)
}

// int32 optype = 2;
inline void ServiceResponsePb::clear_optype() {
  optype_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ServiceResponsePb::_internal_optype() const {
  return optype_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ServiceResponsePb::optype() const {
  // @@protoc_insertion_point(field_get:MyRpc.ServiceResponsePb.optype)
  return _internal_optype();
}
inline void ServiceResponsePb::_internal_set_optype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  optype_ = value;
}
inline void ServiceResponsePb::set_optype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_optype(value);
  // @@protoc_insertion_point(field_set:MyRpc.ServiceResponsePb.optype)
}

// string method = 3;
inline void ServiceResponsePb::clear_method() {
  method_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ServiceResponsePb::method() const {
  // @@protoc_insertion_point(field_get:MyRpc.ServiceResponsePb.method)
  return _internal_method();
}
inline void ServiceResponsePb::set_method(const std::string& value) {
  _internal_set_method(value);
  // @@protoc_insertion_point(field_set:MyRpc.ServiceResponsePb.method)
}
inline std::string* ServiceResponsePb::mutable_method() {
  // @@protoc_insertion_point(field_mutable:MyRpc.ServiceResponsePb.method)
  return _internal_mutable_method();
}
inline const std::string& ServiceResponsePb::_internal_method() const {
  return method_.Get();
}
inline void ServiceResponsePb::_internal_set_method(const std::string& value) {
  
  method_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ServiceResponsePb::set_method(std::string&& value) {
  
  method_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:MyRpc.ServiceResponsePb.method)
}
inline void ServiceResponsePb::set_method(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  method_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:MyRpc.ServiceResponsePb.method)
}
inline void ServiceResponsePb::set_method(const char* value,
    size_t size) {
  
  method_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:MyRpc.ServiceResponsePb.method)
}
inline std::string* ServiceResponsePb::_internal_mutable_method() {
  
  return method_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ServiceResponsePb::release_method() {
  // @@protoc_insertion_point(field_release:MyRpc.ServiceResponsePb.method)
  return method_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ServiceResponsePb::set_allocated_method(std::string* method) {
  if (method != nullptr) {
    
  } else {
    
  }
  method_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), method,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:MyRpc.ServiceResponsePb.method)
}
inline std::string* ServiceResponsePb::unsafe_arena_release_method() {
  // @@protoc_insertion_point(field_unsafe_arena_release:MyRpc.ServiceResponsePb.method)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return method_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ServiceResponsePb::unsafe_arena_set_allocated_method(
    std::string* method) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (method != nullptr) {
    
  } else {
    
  }
  method_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      method, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:MyRpc.ServiceResponsePb.method)
}

// repeated .MyRpc.Host hosts = 4;
inline int ServiceResponsePb::_internal_hosts_size() const {
  return hosts_.size();
}
inline int ServiceResponsePb::hosts_size() const {
  return _internal_hosts_size();
}
inline void ServiceResponsePb::clear_hosts() {
  hosts_.Clear();
}
inline ::MyRpc::Host* ServiceResponsePb::mutable_hosts(int index) {
  // @@protoc_insertion_point(field_mutable:MyRpc.ServiceResponsePb.hosts)
  return hosts_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::MyRpc::Host >*
ServiceResponsePb::mutable_hosts() {
  // @@protoc_insertion_point(field_mutable_list:MyRpc.ServiceResponsePb.hosts)
  return &hosts_;
}
inline const ::MyRpc::Host& ServiceResponsePb::_internal_hosts(int index) const {
  return hosts_.Get(index);
}
inline const ::MyRpc::Host& ServiceResponsePb::hosts(int index) const {
  // @@protoc_insertion_point(field_get:MyRpc.ServiceResponsePb.hosts)
  return _internal_hosts(index);
}
inline ::MyRpc::Host* ServiceResponsePb::_internal_add_hosts() {
  return hosts_.Add();
}
inline ::MyRpc::Host* ServiceResponsePb::add_hosts() {
  // @@protoc_insertion_point(field_add:MyRpc.ServiceResponsePb.hosts)
  return _internal_add_hosts();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::MyRpc::Host >&
ServiceResponsePb::hosts() const {
  // @@protoc_insertion_point(field_list:MyRpc.ServiceResponsePb.hosts)
  return hosts_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace MyRpc

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::MyRpc::Mtype> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MyRpc::Mtype>() {
  return ::MyRpc::Mtype_descriptor();
}
template <> struct is_proto_enum< ::MyRpc::Rcode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MyRpc::Rcode>() {
  return ::MyRpc::Rcode_descriptor();
}
template <> struct is_proto_enum< ::MyRpc::TopicOptype> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MyRpc::TopicOptype>() {
  return ::MyRpc::TopicOptype_descriptor();
}
template <> struct is_proto_enum< ::MyRpc::ServiceOptype> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MyRpc::ServiceOptype>() {
  return ::MyRpc::ServiceOptype_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_message_2eproto
